src/Entity/Patient.php
<?php

namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class Patient
 * @Entity
 * @ORM\Table(name="patients")
 * @package App\Entity
 */


Class Patient
{
    /**
     * @var integer
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id()
     *
     */
    public int $id;

    /**
     * @var string
     * @ORM\Column (name="name", type="string")
     *
     */
    public string $name;

    /**
     * @var integer
     * @ORM\Column(name="resultat_id", type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    public int $promo_id;

    /**
     * @var Resultat $resultat
     * @ORM\ManyToOne(targetEntity="App\Entity\Resultat", fetch="EAGER")
     */
    public Resultat $resultat;


    /**
     * @param string $name
     * @param Resultat|null $resultat
     */
    public function __construct (string $name, ?Resultat $resultat = null){
        $this->name=$name;
        $this->resultat = $resultat;
       // $this -> id = $id;
        }


    public function getNameE(): string
    {
        return $this->name;}

    public function __toString() {
        return $this->name;
    }
}

src/Entity/Resultat.php
<?php

namespace App\Entity;

namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Entity;

/**
 * Class Resultat
 * @Entity
 * @ORM\Table(name="resultats")
 * @package App\Entity
 */


class Resultat
{

    /**
     * @var integer
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id()
     */
    public int $id;


    /**
     * @param string $intitule
     *
     * @ORM\Column(name="intitule", type="string")
     */
    public string $intitule;


    /**
     * @param integer $id
     * @param string $intitule
     */
    public function __construct ( string $intitule, int $id){
        $this->intitule = $intitule;
        $this->id = $id ;}

}

src/Controller/DemoController.php
<?php

namespace App\Controller;

use App\Entity\Patient;
use App\Entity\Resultat;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Config\Framework\RequestConfig;

class DemoController extends AbstractController
{

    #[Route(path: "/new")]
    public function demo(EntityManagerInterface $em)
    {
        $nbrPatient = $this->getDoctrine()->getrepository(Patient::class)->findAll();
        $positive = $em->getRepository(Resultat::class)->findOneBy(['intitule'=>'positive']);
        $negative = $em->getRepository(Resultat::class)->findOneBy(['intitule'=>'negative']);
        $toRedo = $em->getRepository(Resultat::class)->findOneBy(['intitule'=>'toRedo']);

        //$getName = $trucs->findOneBy(["name"=>"Juju"]);

        $etu4 = new Patient("testtt", $negative);

      //  $em->persist($etu3);
        $em->persist($etu4);
        $em->flush ();

        $etu = $em->getRepository(Patient::class)->findAll();
        dump($etu);
        dump($etu4);


        return new Response('Le patient '.$etu4. ' d\'identifiant '.$etu4->id. ' a été créé. Nombre de patient actuel: '.count($nbrPatient));
    }

        #[Route(path: "/patient")]

    public function premiereRoute(EntityManagerInterface $entityManager)
        {
            $liste = $entityManager ->getRepository(Patient::class)->findAll();
            return $this->render('etus.json.twig', ['liste'=>$liste]);
        }



    #[Route(path: "/patient/{id}", methods: ['GET'])]

    public function deuxiemeRoute(EntityManagerInterface $entityManager, int $id)
{
    $etu = $entityManager->getRepository(Patient::class)->find($id);
    //$r = '{"nom":$etu->name.,"id":"'.$etu->$id.'"}';
    return $this->render('etu.json.twig', ['patient'=>$etu]);
}

    #[Route(path: "/patient/{id}", methods: ['DELETE'])]

    public function troisièmeRoute(EntityManagerInterface $entityManager, int $id)
    {
        $etu = $entityManager->getRepository(Patient::class)->find($id);
        $entityManager->remove($etu);
        $entityManager->flush();
        return new Response('ok');
    }

    #[Route(path: "/patient/{id}", methods: ['PUT'])]

    public function quatrièmeRoute(Request $request, EntityManagerInterface $entityManager, int $id)
    {
        $data = json_decode($request->getContent());
        $etu = $entityManager->getRepository(Patient::class)->find($id);
        $etu->name = $data->name;
        $etu->resultat_id = $data->resultat_id;
        $entityManager->flush();
        //return new Response('ok');
        return $this->render('etu.json.twig', ['patient'=>$etu]);
    }



}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {# Run `composer require symfony/webpack-encore-bundle`
           and uncomment the following Encore helpers to start using Symfony UX #}
        {% block stylesheets %}
            {#{{ encore_entry_link_tags('app') }}#}
        {% endblock %}

        {% block javascripts %}
            {#{{ encore_entry_script_tags('app') }}#}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/etu.json.twig
{% block body %}
{#{ "Identifiant = ": "{{ etudiant.id }}",
    "Nom = ": "{{ etudiant.nameE }}"}#}


{% endblock %}
{% block title %}

{% autoescape %}

   "L'identifiant de ce patient est {{ patient.id }}, son nom est {{ patient.name }}. Il est {{ patient.resultat.intitule }}"
{% endautoescape %}

{% endblock %}

templates/etus.json.twig
{% block title %}

{% endblock %}

{% block body %}

{
    "liste": [

        {% for patient in liste %}


        "nom":"{{ patient.name |nl2br}}",
        "id:": "{{ patient.id }}"


        {% if not loop.last %}, {% endif %}

        {% endfor %}
    ]

}


{% endblock %}